production:
  enable_star: true
  port: 9312
  pid_file: /home/luojm/online_shopping/shared/tmp/searchd.pid
  searchd_file_path: /home/luojm/online_shopping/shared/db/sphinx

development:
  ngram_len: 1
  ngram_chars: "U+3000..U+2FA1F"
  port: 9312
  max_matches: 1000
  per_page: 100
  enable_star: true

