require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConstantTextsController do

  # This should return the minimal set of attributes required to create a valid
  # ConstantText. As you add validations to ConstantText, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "contact_state" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConstantTextsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all constant_texts as @constant_texts" do
      constant_text = ConstantText.create! valid_attributes
      get :index, {}, valid_session
      assigns(:constant_texts).should eq([constant_text])
    end
  end

  describe "GET show" do
    it "assigns the requested constant_text as @constant_text" do
      constant_text = ConstantText.create! valid_attributes
      get :show, {:id => constant_text.to_param}, valid_session
      assigns(:constant_text).should eq(constant_text)
    end
  end

  describe "GET new" do
    it "assigns a new constant_text as @constant_text" do
      get :new, {}, valid_session
      assigns(:constant_text).should be_a_new(ConstantText)
    end
  end

  describe "GET edit" do
    it "assigns the requested constant_text as @constant_text" do
      constant_text = ConstantText.create! valid_attributes
      get :edit, {:id => constant_text.to_param}, valid_session
      assigns(:constant_text).should eq(constant_text)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ConstantText" do
        expect {
          post :create, {:constant_text => valid_attributes}, valid_session
        }.to change(ConstantText, :count).by(1)
      end

      it "assigns a newly created constant_text as @constant_text" do
        post :create, {:constant_text => valid_attributes}, valid_session
        assigns(:constant_text).should be_a(ConstantText)
        assigns(:constant_text).should be_persisted
      end

      it "redirects to the created constant_text" do
        post :create, {:constant_text => valid_attributes}, valid_session
        response.should redirect_to(ConstantText.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved constant_text as @constant_text" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConstantText.any_instance.stub(:save).and_return(false)
        post :create, {:constant_text => { "contact_state" => "invalid value" }}, valid_session
        assigns(:constant_text).should be_a_new(ConstantText)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConstantText.any_instance.stub(:save).and_return(false)
        post :create, {:constant_text => { "contact_state" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested constant_text" do
        constant_text = ConstantText.create! valid_attributes
        # Assuming there are no other constant_texts in the database, this
        # specifies that the ConstantText created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ConstantText.any_instance.should_receive(:update_attributes).with({ "contact_state" => "MyText" })
        put :update, {:id => constant_text.to_param, :constant_text => { "contact_state" => "MyText" }}, valid_session
      end

      it "assigns the requested constant_text as @constant_text" do
        constant_text = ConstantText.create! valid_attributes
        put :update, {:id => constant_text.to_param, :constant_text => valid_attributes}, valid_session
        assigns(:constant_text).should eq(constant_text)
      end

      it "redirects to the constant_text" do
        constant_text = ConstantText.create! valid_attributes
        put :update, {:id => constant_text.to_param, :constant_text => valid_attributes}, valid_session
        response.should redirect_to(constant_text)
      end
    end

    describe "with invalid params" do
      it "assigns the constant_text as @constant_text" do
        constant_text = ConstantText.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConstantText.any_instance.stub(:save).and_return(false)
        put :update, {:id => constant_text.to_param, :constant_text => { "contact_state" => "invalid value" }}, valid_session
        assigns(:constant_text).should eq(constant_text)
      end

      it "re-renders the 'edit' template" do
        constant_text = ConstantText.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConstantText.any_instance.stub(:save).and_return(false)
        put :update, {:id => constant_text.to_param, :constant_text => { "contact_state" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested constant_text" do
      constant_text = ConstantText.create! valid_attributes
      expect {
        delete :destroy, {:id => constant_text.to_param}, valid_session
      }.to change(ConstantText, :count).by(-1)
    end

    it "redirects to the constant_texts list" do
      constant_text = ConstantText.create! valid_attributes
      delete :destroy, {:id => constant_text.to_param}, valid_session
      response.should redirect_to(constant_texts_url)
    end
  end

end
